### ISSUE TITLE
[javaScript/3.function] 오타 수정 요청

### ISSUE THREAD

**Issue by sehyunict** [sehyunict/smart#1]
sample2는 익명함수---릏--- 변수에 할당한 것이다. 
-> sample2는 익명함수---를--- 변수에 할당한 것이다.

**Comment by zzinpan** [comment]
### 24라인이 수정되었습니다.
before:
``
sample2는 익명함수릏 변수에 할당한 것이다.
``
after:
``
sample2는 익명함수를 변수에 할당한 것이다.
``
