### ISSUE TITLE
[javaScript/5.object] 오타 수정 요청

### ISSUE THREAD

**Issue by hyun-jong** [sehyunict/smart#11]
객체는 +++줄+++괄호를 이용하여 생성할 수 있다.
-> 객체는 +++중+++괄호를 이용하여 생성할 수 있다.

**Comment by zzinpan** [comment]
before:
객체는 줄괄호를 이용하여 생성할 수 있다.
afther:
객체는 중괄호를 이용하여 생성할 수 있다.

수정했습니다.
