### ISSUE TITLE
[javaScript/3.function] sample6 궁금한 사항

### ISSUE THREAD

**Issue by sehyunict** [sehyunict/smart#2]
sample6에 파라미터인 name과 age는 value로 생각했는데
결과적으로 reference이네요. 어떤 원리로 가능한지 궁금합니다.

아래 코드로 보면 value는 reference를 할 수가 없는데 말이죠.
`var obj = {a:10};
console.log(obj.a);
var aa = obj.a;
aa = 20;
console.log(obj.a);`

**Comment by zzinpan** [comment]
자바스크립트에선 **object만 reference를 갖습니다.**
그 외는 전부 값으로 생각하면 됩니다.

댓글에 예제를 분석해보면,

```javascript
var obj = {a:10};
console.log( obj === window.obj ); // true
console.log( obj.a === window.obj.a ); // true

var aa = obj.a; // aa = 10;
// obj.a는 값이니까 aa에는 값이 복사됩니다.
// 이때 aa는 객체가 아니라 값이 할당되었으니까 aa는 obj와 관련이 없습니다.

//  aa의 값을 바꿔봤자 obj에 영향이 없습니다.
aa = 20; // aa = 20;
console.log( obj.a ); // 10
```
<br>
javascript에선 각 스코프 별로 변수를 관리하는 객체를 갖습니다.
전역 스코프에선 window가 변수관리 객체입니다.
로컬 스코프(함수)에선 arguments가 변수관리 객체입니다.

```javascript
var no = 0; // 이 코드는 사실 window.no = 0; 과 같습니다.
console.log( no ); // 0
console.log( window.no ); // 0

no = -1; // window.no를 -1로 바꿨습니다.
console.log( no ); // -1
console.log( window.no ); // -1

// no를 변경했지만, window.no가 변경됩니다.
```
이 예제를 로컬스코프에 적용해서 생각하시면, 이해가 쉬울 것 같네요.
<br>

**Comment by hyun-jong** [comment]
local scope에서 arguments가 변수 관리 객체로 이해하면 되는군요.
감사합니다.
